version: "3.7"

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: instaimg_bot
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
    - ./telegram_bot_token:/opt/bot/telegram_bot_token
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.3-bionic
    environment:
      MONGO_INITDB_DATABASE: instaimg
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata: