on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull new code and restart server
        uses: appleboy/ssh-action@e59c0ee97a7e5240ed9eb489791adbb9c9ac7f6b
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: cd /opt/instaimg && git pull && docker-compose up --build --always-recreate-deps -d